name: AI Moderator
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  check-org-membership:
    runs-on: ubuntu-latest
    outputs:
      is-member: ${{ steps.check.outputs.is-member }}
    steps:
      - name: Check if actor is org member
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ORG="bitcoin"
          ACTOR="${{ github.actor }}"
          if gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/orgs/${ORG}/members/${ACTOR}" --silent 2>/dev/null; then
            echo "is-member=true" >> "$GITHUB_OUTPUT"
            echo "${ACTOR} is a member of ${ORG}"
          else
            echo "is-member=false" >> "$GITHUB_OUTPUT"
            echo "${ACTOR} is not a member of ${ORG}"
          fi
  spam-detection:
    needs: check-org-membership
    if: needs.check-org-membership.outputs.is-member == 'false'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      models: read
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: github/ai-moderator@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          spam-label: 'spam'
          ai-label: 'ai-generated'
          minimize-detected-comments: true
          enable-spam-detection: true
          enable-link-spam-detection: true
          enable-ai-detection: true
          custom-prompt-path: '.github/prompts/bitcoin-spam.prompt.yml'
